version: "3.9"
services:
  # Spring Application
  agu-prediction-system:
    container_name: agu-prediction-system
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-back-end
    environment:
      - PYTHON_SCRIPT_PATH = /usr/app/scripts
    entrypoint: [ "java -jar /usr/app/AGUPredictionSystem-0.0.1-SNAPSHOT.jar" ]
    ports:
      - "8082:8080"
