version: "3.9"
services:
  # Spring Application
  agu-prediction-system:
    container_name: agu-data-system
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-spring
    environment:
      - PYTHON_SCRIPT_PATH = /../code/python/scripts
    entrypoint: [ "java -jar /usr/app/AGUPredictionSystem-0.0.1-SNAPSHOT.jar" ]
    ports:
      - "8082:8080"
